apiVersion: apps/v1
kind: Deployment
metadata:
  name: question-service
  labels:
    app: question-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: question-service
  template:
    metadata:
      labels:
        app: question-service
    spec:
      containers:
        - name: question-service
          image: asia-southeast1-docker.pkg.dev/crucial-mender-402111/peerprep/question:latest
          ports:
            - name: qn-service
              containerPort: 8002
          env:
          - name: DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: db-admin
                key: db-username
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-admin
                key: db-password
      restartPolicy: Always
